# Numpy

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a1 = np.array([1,2,3,4])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a1

array([1, 2, 3, 4])

In [6]:
a1.shape

(4,)

In [9]:
np.__version__

'2.2.3'

In [10]:
a2 = np.array(['mar',1,True,6.35])

In [11]:
a2

array(['mar', '1', 'True', '6.35'], dtype='<U32')

In [12]:
np.array([1,True,6.35])

array([1.  , 1.  , 6.35])

In [13]:
a2 = np.array([[1,2,3],[4,5,6]])

In [14]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
a = None

In [20]:
a

In [21]:
print(a)

None


In [22]:
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
a3.shape

(3, 3)

In [24]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
a2.shape

(2, 3)

In [26]:
np.zeros(3)

array([0., 0., 0.])

In [27]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
a4 = np.zeros(9)

In [29]:
a4.shape

(9,)

In [32]:
a5 = np.zeros((3,3))

In [33]:
a5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
a5.shape

(3, 3)

In [37]:
np.zeros((10,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
np.ones(4)

array([1., 1., 1., 1.])

In [39]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.ones(shape=(2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [5]:
np.ones(shape=(2,3),dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [41]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [42]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Broadcasting

In [44]:
input_list = [1,2,3,4]

# Expected Output
# output_list = [2,4,6,8]

In [48]:
output_list = []
for item in input_list:
    # print(item*2)
    output_list.append(item*2)
print(output_list)

[2, 4, 6, 8]


In [50]:
# Using List comprehension
output_list = [item*2 for item in input_list]
print(output_list)

[2, 4, 6, 8]


In [51]:
input_list * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [52]:
my_array = np.array([1,2,3,4])

In [53]:
my_array * 2

array([2, 4, 6, 8])

In [54]:
my_array

array([1, 2, 3, 4])

In [15]:
# From input list [1,2,3,4], create ouput list where each item is mutiplied by 2 

input_list = [1,2,3,4]
my_array = np.array(input_list)
print(my_array)
my_array = my_array * 2
print(f"result: {my_array}")
print(list(my_array))
output_list = my_array.tolist()
print(output_list)

[1 2 3 4]
result: [2 4 6 8]
[np.int64(2), np.int64(4), np.int64(6), np.int64(8)]
[2, 4, 6, 8]


In [17]:
(np.array([1,2,3,4]) * 2).tolist()

[2, 4, 6, 8]

In [12]:
input_list = [1,2,3,4]
print((np.array(input_list)*2).tolist())

[2, 4, 6, 8]


In [ ]:
my_array * 2

array([2, 4, 6, 8])

In [60]:
list(my_array * 2)

[np.int64(2), np.int64(4), np.int64(6), np.int64(8)]

In [64]:
my_array

array([1, 2, 3, 4])

In [66]:
my_array + 10
# This is called broadcasting

array([11, 12, 13, 14])

In [69]:
a = np.array([[1,2],[3,4]])
b = np.array([[10,11],[12,13]])
print(f"a: {a}")
print(f"b:{b}")

a: [[1 2]
 [3 4]]
b:[[10 11]
 [12 13]]


In [70]:
a + b

array([[11, 13],
       [15, 17]])

In [71]:
a - b

array([[-9, -9],
       [-9, -9]])

In [72]:
a * b

array([[10, 22],
       [36, 52]])

In [73]:
a / b

array([[0.1       , 0.18181818],
       [0.25      , 0.30769231]])

In [74]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [75]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
a.shape

(3, 4)

In [77]:
a[0]

array([1, 2, 3, 4])

In [79]:
a[2]

array([ 9, 10, 11, 12])

In [80]:
a[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [82]:
a.shape

(3, 4)

In [83]:
a[0,0]

np.int64(1)

In [84]:
a[2,1]

np.int64(10)

In [85]:
a[0,0:3]

array([1, 2, 3])

In [86]:
a[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [87]:
a[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [88]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
a[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [91]:
a[1,2]

np.int64(7)

In [92]:
a[1,2] = 70

In [93]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6, 70,  8],
       [ 9, 10, 11, 12]])

In [95]:
a[2,1] = a[2,1] / 6

In [96]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6, 70,  8],
       [ 9,  1, 11, 12]])

In [97]:
10/6

1.6666666666666667

In [98]:
int(10/6)

1

In [99]:
np.array([1,2,3,4],dtype=float)

array([1., 2., 3., 4.])

In [101]:
np.array([[1,2,3,4],[5,6,7,8]],dtype=str)

array([['1', '2', '3', '4'],
       ['5', '6', '7', '8']], dtype='<U1')

In [106]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [107]:
list(range(2,19))

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

In [108]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [111]:
np.arange(1,1300)

array([   1,    2,    3, ..., 1297, 1298, 1299], shape=(1299,))

In [112]:
b = np.arange(1,13)

In [113]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [114]:
b.shape

(12,)

In [115]:
b.reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [116]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [117]:
b = b.reshape((3,4))

In [118]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [119]:
6 * 5

30

In [122]:
c = np.arange(30).reshape((5,6))
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])